### PR TITLE
Unfold 1.2

### PR DESCRIPTION
**Pull request by behinger**
I think it is time to bring in some changes - I also think this is the reason why the activity counter at https://github.com/unfoldtoolbox/ looks unfair towards unfold.jl.

Whats new?
- uf_se (a bit preliminary to be honest, maybe set back? I think without modelling AR this is not super useful)
- uf_rejection-functions
- lot's of bugfixes

@olafdimigen what do you think?

### CODE REVIEW

**Comment by olafdimigen** [comment]
Nice. I agree it's time for new release.

**Comment by behinger** [comment]
delay uf_se or release with a warning (a bit weird, no?)

**Comment by olafdimigen** [comment]
Ideally, only features that are stable and also hard to misinterpret should enter releases. I'd have to look into it more carefully, since I have not tested uf_se yet.

**Comment by behinger** [comment]
I removed uf_se for now. Will push it to another branch

**Pull request merged**
